### ISSUE TITLE
Unable to import a CSV or XLS file when importing as a Local File

### ISSUE THREAD

**Issue by beaner011** [teableio/teable#1360]
**Describe the bug**
I am unable to successfully import a CSV or XLS file when importing as a "Local File".  After selecting the file, it quickly goes to "analyzing" and then sits there for a bit before timing out with a 500 internal server error.  When I look at the uploads/private/import directory, I can see that a file was created containing the data.  If I click the generated "attachmentURL" found in the logs, it downloads that file as a CSV and I can view the data in Excel.

I can see the "failed, reason: connect ETIMEDOUT 10.180.73.172:8085" in the logs associated with an upload attempt (attached), but I cannot figure out the reason for the timeout since access of Teable via that IP/port works fine for all other functionality.

I have tried importing from both Chrome and Firefox as well as from both Windows and Ubuntu.

The CSV file I have been using for testing can be found at https://people.sc.fsu.edu/~jburkardt/data/csv/trees.csv (no affiliation to this data, just needed something for testing).  I have tried a few other CSV/XLS files with the same result.

Importing via "Link(URL)" works as expected.

**To Reproduce**
Within a Base, use the "+" to import a CSV or XLS file as "Local File" (happens with manual file selection or drag and drop).

**Expected behavior**
Data is imported into a table via an uploaded CSV or XLS file

** Client (please complete the following information):**

- OS: Windows 11 and Ubuntu 24.04
- Browser: Chrome and Firefox
- Version: 133 and 135

**Platform (Please tell us which deployment version you are using)**
Podman 1.6.0-alpha+build.814

**Additional context**
I am hosting Teable in a bit of an unconventional way.  I'm using a Podman pod since this is being run in an enterprise environment and we do not have a Docker license.  It is running within an unprivileged Proxmox LXC (Debian 12).  As stated above, Teable looks to be able to write to its data directory just fine.  Data storage is a mount point only used by the Teable LXC (no bind mounts or anything similar that can cause permissions issues).  I'm not sure if it could somehow be related to Podman's networking, which I'm admittedly much less familiar with vs. Docker.  Teable is functioning normal otherwise with regards to accessibility and intra-container communication, which would seem to point to networking not being the issue.  Overall, I have not seen anything that obviously points to my setup being the underlying cause of the inability to import.

I do typically access Teable over a VPN (Tailscale) connection, but I have also tried uploading the CSV from a host on the same subnet with the same failure.

I have been accessing Teable non-SSL for the most part (not in production yet), but have also tried accessing via SSL with the same failure.

Postgres 15.4 is the database backend and Redis 7.2.4 is the cache backend, both running as part of the same Podman pod.

[teableImportFailLogs.log](https://github.com/user-attachments/files/19026917/teableImportFailLogs.log)

**Comment by caoxing9** [comment]
Could you share the docker config, shielding sensitive info.
What's more, base on your context, you could try following suggestions.
1. check podman network config
  `podman pod inspect <pod name>`
  `podman inspect <container ID> --format '{{.NetworkSettings.Networks}}'`
2. try using host network mode
  `podman pod create --name teable-pod --network host`

I hope these could work, lookward your feedback~

**Comment by beaner011** [comment]
Sorry for the delay in getting back to you.  My Podman config (Kubernetes YAML format) is below.  I use "podman kube play teable.yaml" to create and start the pod.  I'm going to try out your recommendations today.  Thanks!

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: teable
  name: teable
spec:
  containers:

  # TEABLE APPLICATION
  - name: teable
    image: ghcr.io/teableio/teable:latest
    env:
    - name: SECRET_KEY
      value: <SECRET_KEY>
    - name: PUBLIC_ORIGIN
      value: http://10.180.73.172:8085
    - name: NEXT_ENV_IMAGES_ALL_REMOTE
      value: true
    - name: LOG_LEVEL
      value: debug
    - name: BACKEND_MAIL_HOST
      value: smtp.foo.com
    - name: BACKEND_MAIL_PORT
      value: 465
    - name: BACKEND_MAIL_SECURE
      value: true
    - name: BACKEND_MAIL_SENDER
      value: mail@foo.com
    - name: BACKEND_MAIL_SENDER_NAME
      value: "Mail Sender"
    - name: BACKEND_MAIL_AUTH_USER
      value: mail@foo.com
    - name: BACKEND_MAIL_AUTH_PASS
      value: <MAIL_PASSWORD>
    - name: PRISMA_DATABASE_URL
      value: postgresql://teable:<POSTGRES_PASSWORD>@localhost:5432/teable
    - name: BACKEND_CACHE_PROVIDER
      value: redis
    - name: BACKEND_CACHE_REDIS_URI
      value: redis://default:<REDIS_PASSWORD>@localhost:6379/0
    ports:
    - containerPort: 3000
      hostPort: 8080
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /app/.assets
      name: teable-data

  # POSTGRESQL
  - name: teable-db
    image: docker.io/library/postgres:15.4
    args:
    - postgres
    env:
    - name: POSTGRES_HOST
      value: localhost
    - name: POSTGRES_PORT
      value: 5432
    - name: POSTGRES_DB
      value: teable
    - name: POSTGRES_USER
      value: teable
    - name: POSTGRES_PASSWORD
      value: <POSTGRES_PASSWORD>
    ports:
    - containerPort: 5432
      hostPort: 42345
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: teable-db

  # REDIS
  - name: teable-cache
    image: docker.io/library/redis:7.2.4
    args:
    - redis-server
    - --appendonly
    - yes
    - --requirepass
    - <REDIS_PASSWORD>
    env:
    - name: REDIS_HOST
      value: localhost
    - name: REDIS_PORT
      value: 6379
    - name: REDIS_DB
      value: 0
    - name: REDIS_PASSWORD
      value: <REDIS_PASSWORD>
    ports:
    - containerPort: 6379
      hostPort: 6379
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /data
      name: teable-cache

  - name: teable-db-migrate
    image: ghcr.io/teableio/teable-db-migrate:latest
    env:
    - name: PRISMA_DATABASE_URL
      value: postgresql://teable:<POSTGRES_PASSWORD>@localhost:5432/teable
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE

  enableServiceLinks: false
  hostname: teable
  restartPolicy: Never

  volumes:
  - hostPath:
      path: /mnt/teable-data/teable/data
      type: Directory
    name: teable-data
  - hostPath:
      path: /mnt/teable-data/postgresql
      type: Directory
    name: teable-db
  - hostPath:
      path: /mnt/teable-data/teable/cache
      type: Directory
    name: teable-cache
```

**Comment by beaner011** [comment]
Switching to host network made seems to have resolved the issue.  Thanks again!

For anyone who may come across this in the future, my working pod config is below.  I added "hostNetwork: true" and removed all of the port mappings.  I also added a variable declaration for PORT since I want to run Teable on a different one.

I imagine there's a way to get things working properly without using host network mode, but for my situation this will work fine.

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: teable
  name: teable
spec:
  containers:

  # TEABLE APPLICATION
  - name: teable
    image: ghcr.io/teableio/teable:latest
    env:
    - name: SECRET_KEY
      value: <SECRET_KEY>
    - name: PORT
      value: 8085
    - name: PUBLIC_ORIGIN
      value: http://10.180.73.172:8085
    - name: NEXT_ENV_IMAGES_ALL_REMOTE
      value: true
    - name: LOG_LEVEL
      value: debug
    - name: BACKEND_MAIL_HOST
      value: smtp.foo.com
    - name: BACKEND_MAIL_PORT
      value: 465
    - name: BACKEND_MAIL_SECURE
      value: true
    - name: BACKEND_MAIL_SENDER
      value: mail@foo.com
    - name: BACKEND_MAIL_SENDER_NAME
      value: "Mail Sender"
    - name: BACKEND_MAIL_AUTH_USER
      value: mail@foo.com
    - name: BACKEND_MAIL_AUTH_PASS
      value: <MAIL_PASSWORD>
    - name: PRISMA_DATABASE_URL
      value: postgresql://teable:<POSTGRES_PASSWORD>@localhost:5432/teable
    - name: BACKEND_CACHE_PROVIDER
      value: redis
    - name: BACKEND_CACHE_REDIS_URI
      value: redis://default:<REDIS_PASSWORD>@localhost:6379/0
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /app/.assets
      name: teable-data

  # POSTGRESQL
  - name: teable-db
    image: docker.io/library/postgres:15.4
    args:
    - postgres
    env:
    - name: POSTGRES_HOST
      value: localhost
    - name: POSTGRES_PORT
      value: 5432
    - name: POSTGRES_DB
      value: teable
    - name: POSTGRES_USER
      value: teable
    - name: POSTGRES_PASSWORD
      value: <POSTGRES_PASSWORD>
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: teable-db

  # REDIS
  - name: teable-cache
    image: docker.io/library/redis:7.2.4
    args:
    - redis-server
    - --appendonly
    - yes
    - --requirepass
    - <REDIS_PASSWORD>
    env:
    - name: REDIS_HOST
      value: localhost
    - name: REDIS_PORT
      value: 6379
    - name: REDIS_DB
      value: 0
    - name: REDIS_PASSWORD
      value: <REDIS_PASSWORD>
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /data
      name: teable-cache

  - name: teable-db-migrate
    image: ghcr.io/teableio/teable-db-migrate:latest
    env:
    - name: PRISMA_DATABASE_URL
      value: postgresql://teable:<POSTGRES_PASSWORD>@localhost:5432/teable
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE

  enableServiceLinks: false
  hostname: teable
  hostNetwork: true
  restartPolicy: Never

  volumes:
  - hostPath:
      path: /mnt/teable-data/teable/data
      type: Directory
    name: teable-data
  - hostPath:
      path: /mnt/teable-data/postgresql
      type: Directory
    name: teable-db
  - hostPath:
      path: /mnt/teable-data/teable/cache
      type: Directory
    name: teable-cache
```
