### ISSUE TITLE
Self-Hosted - 404

### ISSUE THREAD

**Issue by AddiXz** [teableio/teable#1395]
Hi Team, 

I've been trying to setup Teable locally. 
Sadly I keep running into issues. 

At first I setup the container as per your guidance on https://help.teable.io/en/deploy/docker.
I was not able to connect at all. Later I found out that port 3000 is not used, but rather 3002.
After adjusting it, I was able to connect, but instantly run into a " 404 - This page could not be found".

This is my docker-compose:

```
### PostgreSQL - Databases
  postgres:
    container_name: FinPost
    image: 'postgres:16.4'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${postgresUser2}
      - POSTGRES_PASSWORD=${postgresPW2}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ~/DOCKER/FinPost/db-data/:/var/lib/postgresql/data/
    command: -p ${POSTGRES_PORT}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
  
### TEABLE CONTAINERS
  teable:
    container_name: teable
    image: ghcr.io/teableio/teable:latest
    restart: unless-stopped
    ports:
      - '5006:3002'
    volumes:
      - ${MAIN_FOLDER}Teable/teable-data:/app/.assets:rw
    environment:
      # Core
      - PUBLIC_ORIGIN=${td}
      - LOG_LEVEL=debug
      - SECRET_KEY=${dd_st}
      - NEXT_ENV_IMAGES_ALL_REMOTE=true
      # storage
      - BACKEND_STORAGE_PROVIDER=minio
      - BACKEND_STORAGE_MINIO_ENDPOINT=minio.${dn}
      - BACKEND_STORAGE_MINIO_ACCESS_KEY=${N8N_STORAGE_ACCESS_KEY}
      - BACKEND_STORAGE_MINIO_SECRET_KEY=${N8N_STORAGE_ACCESS_SECRET}
      # AUTH
      - SOCIAL_AUTH_PROVIDERS=oidc
      - BACKEND_OIDC_CLIENT_ID=${OIDC_C}
      - BACKEND_OIDC_CLIENT_SECRET=${OIDC_CS}
      - BACKEND_OIDC_CALLBACK_URL=${td}/api/auth/oidc/callback
      - BACKEND_OIDC_USER_INFO_URL=${kdc}/protocol/openid-connect/userinfo
      - BACKEND_OIDC_TOKEN_URL=${kdc}/protocol/openid-connect/token
      - BACKEND_OIDC_AUTHORIZATION_URL=${kdc}/protocol/openid-connect/auth
      - BACKEND_OIDC_ISSUER=${kdc}
      # DATABASE
      - POSTGRES_DB=${POSTGRES_TDB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${postgresUser}
      - POSTGRES_PASSWORD=${postgresPW}
      # REDIS HOST
      - REDIS_HOST=teable-redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      # Email
      - BACKEND_MAIL_HOST=${SMTP_HOST}
      - BACKEND_MAIL_PORT=${SMTP_PORT}
      - BACKEND_MAIL_SECURE='true'
      - BACKEND_MAIL_SENDER=${SMTP_FROM_EMAIL}
      - BACKEND_MAIL_AUTH_USER=${SMTP_USER}
      - BACKEND_MAIL_AUTH_PASS=${SMTP_PASSWORD}
      - BACKEND_MAIL_SENDER_NAME=Teable System notification
    depends_on:
      teable-db-migrate:
        condition: service_completed_successfully
      teable-redis:
        condition: service_healthy

  teable-db-migrate:
    container_name: teable-db-migrator
    image: ghcr.io/teableio/teable-db-migrate:latest
    environment:
      - PRISMA_DATABASE_URL=postgresql://${postgresUser}:${postgresPW}@postgres:${POSTGRES_PORT}/${POSTGRES_TDB}
    depends_on:
      - postgres

  teable-redis:
    container_name: teable-redis
    image: redis:7.2.4
    restart: unless-stopped
    expose:
      - '6379'
    volumes:
      - ${MAIN_FOLDER}Teable/teable-cache:/data:rw
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 3s
      retries: 3
```

Not sure what's causing the 404..
The logs in the container do not show any warnings, failures or errors..

Can you help me understand where the issue may lie?

Edit- 
After changing the port back to port 3000 I get connection refused and this in the logs:
```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ETIMEDOUT',
  [errors]: [
    Error: connect ETIMEDOUT 104.21.61.209:9000
        at createConnectionError (node:net:1634:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
        at listOnTimeout (node:internal/timers:575:11)
--
      port: 9000
    },
    Error: connect ETIMEDOUT 172.67.215.35:9000
        at createConnectionError (node:net:1634:14)
        at afterConnectMultiple (node:net:1664:40)
        at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
```
