### ISSUE TITLE
Application becomes inaccessible when modifying exposed port (only port 3000 works)

### ISSUE THREAD

**Issue by HansYeoh** [teableio/teable#1407]
**Describe the bug**
When changing the exposed port in docker-compose.yaml and corresponding .env file settings, the application becomes inaccessible. Reverting to port 3000 restores normal access.

**To Reproduce**
1. Change the exposed port in docker-compose.yaml (e.g., from 3000 to 10080)
2. Update the corresponding port setting in .env file
3. Restart the Docker containers
4. Attempt to access the application at the new port
5. Observe connection failure
6. Revert to port 3000 in both files and restart
7. Application becomes accessible again

**Expected behavior**
After changing the exposed port in both docker-compose.yaml and .env file, the application should be accessible at the new port.

**Environment Information:**
- Docker version: 27.5.1, build 9f9e405
- Docker Compose version: v2.32.4
- OS: Ubuntu 20.04.6

**Screenshots**

<img width="1077" alt="Image" src="https://github.com/user-attachments/assets/a3108c2f-396b-43c6-91a1-d6c158154986" />

<img width="1314" alt="Image" src="https://github.com/user-attachments/assets/2466ff87-d58f-403d-8fdd-c1776339e028" />

<img width="1314" alt="Image" src="https://github.com/user-attachments/assets/5a8a3d6b-db1a-4ff5-a297-c3611a18bc35" />

**Configuration Files**
- docker-compose.yaml
```yaml
services:
  teable:
    image: registry.cn-shenzhen.aliyuncs.com/teable/teable:latest
    restart: always
    ports:
      - '10080:3000'
    volumes:
      - ./volumes/teable-data:/app/.assets:rw
    env_file:
      - .env
    environment:
      - NEXT_ENV_IMAGES_ALL_REMOTE=true
    networks:
      - teable
    depends_on:
      teable-db-migrate:
        condition: service_completed_successfully
      teable-cache:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 3

  teable-db:
    image: registry.cn-shenzhen.aliyuncs.com/teable/postgres:15.4
    restart: always
    ports:
      - '10432:5432'
    volumes:
      - ./volumes/teable-db:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - teable
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  teable-db-migrate:
    image: registry.cn-shenzhen.aliyuncs.com/teable/teable-db-migrate:latest
    environment:
      - PRISMA_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    networks:
      - teable
    depends_on:
      teable-db:
        condition: service_healthy

  teable-cache:
    image: registry.cn-shenzhen.aliyuncs.com/teable/redis:7.2.4
    restart: always
    expose:
      - '6379'
    volumes:
      - ./volumes/teable-cache:/data:rw
    networks:
      - teable
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 3s
      retries: 3

  teable-storage:
    image: registry.cn-shenzhen.aliyuncs.com/teable/minio:RELEASE.2024-02-17T01-15-57Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - ./volumes/teable-storage:/data:rw
    networks:
      - teable
    command: server /data --console-address ":9001"
  createbuckets:
    image: registry.cn-shenzhen.aliyuncs.com/teable/mc
    networks:
      - teable
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set teable-storage http://teable-storage:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb teable-storage/public;
      /usr/bin/mc anonymous set public teable-storage/public;
      /usr/bin/mc mb teable-storage/private;
      exit 0;
      "
    depends_on:
      teable-storage:
        condition: service_started

networks:
  teable:
    name: teable-network
```
- .env
```
# 替换下面默认密码, 推荐使用 8 位以上的强密码。
POSTGRES_PASSWORD=6pY5QfbDosZA7N3M
REDIS_PASSWORD=V6KmoZHk4Ak3xcyX
SECRET_KEY=7VLdGuNVb63f683v

# 如果启用 https，请将 PROTOCAL 设置为 https。
PROTOCAL=http
# 请将 PUBLIC_HOST 设置为当前部署的主机的 IP 或者域名。无法使用 localhost 或 127.0.0.1。
PUBLIC_HOST=192.168.100.188
# 请将最后端口修改为正式访问地址的端口，如 为 80 或 443 可去掉:和端口号。
PUBLIC_ORIGIN=http://192.168.100.188:10080

# ---------------------

# Postgres
POSTGRES_HOST=teable-db
POSTGRES_PORT=5432
POSTGRES_DB=teable
POSTGRES_USER=teable

# Redis
REDIS_HOST=teable-cache
REDIS_PORT=6379
REDIS_DB=0

# Minio
MINIO_ACCESS_KEY=teable_minio_access
MINIO_SECRET_KEY=${SECRET_KEY}

# App
PRISMA_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
BACKEND_CACHE_PROVIDER=redis
BACKEND_CACHE_REDIS_URI=redis://default:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
BACKEND_STORAGE_PROVIDER=minio
BACKEND_STORAGE_PUBLIC_BUCKET=public
BACKEND_STORAGE_PRIVATE_BUCKET=private
BACKEND_STORAGE_MINIO_USE_SSL=false # 如果启用 https 请修改该值为 true
BACKEND_STORAGE_MINIO_ENDPOINT=${PUBLIC_HOST}
BACKEND_STORAGE_MINIO_PORT=9000
BACKEND_STORAGE_MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
BACKEND_STORAGE_MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
STORAGE_PREFIX=${PROTOCAL}://${PUBLIC_HOST}:${BACKEND_STORAGE_MINIO_PORT}

# 
PUBLIC_DATABASE_PROXY=192.168.100.188:10432

```
