### ISSUE TITLE
Error: Invalid DATABASE_URL: Invalid URL

### ISSUE THREAD

**Issue by OPSTime** [teableio/teable#1566]
docker-compose up -d

error:
```
teable_1     | Running database migration...
teable_1     | DB Migrate Starting...
teable_1     | file:///app/scripts/db-migrate.mjs:24
teable_1     |     throw new Error(`Invalid DATABASE_URL: ${error.message}`);
teable_1     |           ^
teable_1     | 
teable_1     | Error: Invalid DATABASE_URL: Invalid URL
teable_1     |     at parseDsn (file:///app/scripts/db-migrate.mjs:24:11)
teable_1     |     at file:///app/scripts/db-migrate.mjs:58:32
teable_1     |     at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
teable_1     |     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
teable_1     |     at async loadESM (node:internal/process/esm_loader:34:7)
teable_1     |     at async handleMainPromise (node:internal/modules/run_main:66:12)
teable_1     | 
teable_1     | Node.js v20.9.0
teable_1     | Database migration failed
```

.env:
```
POSTGRES_PASSWORD=xxxxxx
SECRET_KEY=xxxxxx

PUBLIC_ORIGIN=http://192.168.12.11:3000

POSTGRES_HOST=teable-db
POSTGRES_PORT=5432
POSTGRES_DB=teable
POSTGRES_USER=teable


PRISMA_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

```
docker-compose.yaml:
```
version: "3"
services:
  teable:
    image: registry.cn-shenzhen.aliyuncs.com/teable/teable:latest
    #image: registry.cn-shenzhen.aliyuncs.com/teable/teable:1.7.0-alpha-build.867-amd64
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - teable-data:/app/.assets:rw
    env_file:
      - .env
    environment:
      - NEXT_ENV_IMAGES_ALL_REMOTE=true
    depends_on:
      - teable-db

  teable-db:
    image: registry.cn-shenzhen.aliyuncs.com/teable/postgres:15.4
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - teable-db:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  teable-db: {}
  teable-data: {}
  teable-cache: {}
```
