### ISSUE TITLE
Help: How do I connect to a local pg database that is not in docker

### ISSUE THREAD

**Issue by lucktoo** [teableio/teable#533]
请问怎么连接 不是在docker里面的,本地的pg数据库
求助

**Comment by tea-artist** [comment]
To facilitate community search and reading, please use English for any discussions. 
You can choose a [docker-compose example](dockers/examples) and change the Postgres env variables in the `.env` file to your external database information as follows:

```sh
# Postgres
POSTGRES_HOST=teable-db
POSTGRES_PORT=5432
POSTGRES_DB=example
POSTGRES_USER=example
POSTGRES_PASSWORD=example2password
```

Also, remove the teable-db service in the docker-compose.yaml:

**Comment by lucktoo** [comment]
请问是 改那个 .env文件呢?
文件下有2个.env文件
1./Users/bluesky/Documents/teable-develop/dockers/examples/standalone/.env
2./Users/bluesky/Documents/teable-develop/dockers/.env
3./Users/bluesky/Documents/teable-develop/dockers/examples/standalone/docker-compose.yaml   这个文件?
如下我注释掉了
teable-db:
  #   image: postgres:15.4
  #   restart: always
  #   ports:
  #     - '42345:5432'
  #   volumes:
  #     - teable-db:/var/lib/postgresql/data:rw
  #     # you may use a bind-mounted host directory instead,
  #     # so that it is harder to accidentally remove the volume and lose all your data!
  #     # - ./docker/db/data:/var/lib/postgresql/data:rw
  #   environment:
  #     - TZ=${TIMEZONE}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   networks:
  #     - teable-standalone
  #   healthcheck:
  #     test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
  #     interval: 10s
  #     timeout: 3s
  #     retries: 3
  
  终端报错:
  docker-compose up -d
service "teable-db-migrate" depends on undefined service teable-db: invalid compose project

**Comment by lucktoo** [comment]
请问是 改那个 .env文件呢?求助
请问怎么连接 不是在docker里面的，本地的pg数据库

文件下有2个.env文件
1./Users/bluesky/Documents/teable-develop/dockers/examples/standalone/.env
2./Users/bluesky/Documents/teable-develop/dockers/.env
3./Users/bluesky/Documents/teable-develop/dockers/examples/standalone/docker-compose.yaml   这个文件?
如下我注释掉了
```
teable-db:
  #   image: postgres:15.4
  #   restart: always
  #   ports:
  #     - '42345:5432'
  #   volumes:
  #     - teable-db:/var/lib/postgresql/data:rw
  #     # you may use a bind-mounted host directory instead,
  #     # so that it is harder to accidentally remove the volume and lose all your data!
  #     # - ./docker/db/data:/var/lib/postgresql/data:rw
  #   environment:
  #     - TZ=${TIMEZONE}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   networks:
  #     - teable-standalone
  #   healthcheck:
  #     test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
  #     interval: 10s
  #     timeout: 3s
  #     retries: 3
```
  
  终端报错:
  docker-compose up -d
service "teable-db-migrate" depends on undefined service teable-db: invalid compose project

**Comment by tea-artist** [comment]
1. change the env under standalone/.env
2. replace standalone/docker-compose.yaml  with the following content
```
version: '3.9'
services:
  teable:
    image: ghcr.io/teableio/teable:latest
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - teable-data:/app/.assets:rw
      # you may use a bind-mounted host directory instead,
      # so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/teable/data:/app/.assets:rw
    env_file:
      - .env
    environment:
      - TZ=${TIMEZONE}
      - NEXT_ENV_IMAGES_ALL_REMOTE=true
    networks:
      - teable-standalone
    depends_on:
      teable-db-migrate:
        condition: service_completed_successfully
  teable-db-migrate:
    image: ghcr.io/teableio/teable-db-migrate:latest
    environment:
      - TZ=${TIMEZONE}
      - PRISMA_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    networks:
      - teable-standalone

networks:
  teable-standalone:
    name: teable-standalone-network
    driver: bridge

volumes:
  teable-data: {}
```
